import localFont from "next/font/local";
import "./globals.css";

const fontPretendard = localFont({
  src: [
    { path: "./_fonts/Pretendard-Bold.woff2", weight: "700" },
    { path: "./_fonts/Pretendard-SemiBold.woff2", weight: "600" },
    { path: "./_fonts/Pretendard-Medium.woff2", weight: "500" },
    { path: "./_fonts/Pretendard-Regular.woff2", weight: "400" },
  ],
  variable: "--font-pretendard",
  display: "swap",
});

export const metadata = {
  title: "판다마켓",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={fontPretendard.className}>
      <body>{children}</body>
    </html>
  );
}
